version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:Saadsaad1@postgres:5432/advoco?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saadsaad1
      POSTGRES_DB: advoco
    ports:
      - '5432:5432'
