import 'module-alias/register';
import express from 'express';
import { authRoutes, profileRoutes, clientRoutes } from './routes';
import bodyParser from 'body-parser';
const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/user/profile', profileRoutes);
app.use('/client', clientRoutes);
const port = process.env.PORT || 8000;
app.listen(port, () => console.log(`Server is running... on port ${port}`));
